trigger:
  branches:
    include:
    - main


pool:
  name: Default

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'SWE-Assignment1'
    repository: 'SWE-Assignment1'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Docker@2
  displayName: 'Push Docker image'
  inputs:
    containerRegistry: 'SWE-Assignment1'
    repository: 'SWE-Assignment1'
    command: 'push'
    tags: 'latest'

variables:
- name: DOCKER_BUILDKIT
  value: 1